### ISSUE TITLE
Unable to edit Git Project

### ISSUE THREAD

**Issue by troelslenda** [reload/aegir-project#9]
![Screen Shot 2012-12-19 at 9 21 02 AM](https://f.cloud.github.com/assets/263060/21491/3f4e01fc-49b5-11e2-8fa8-6034bfd1fa20.png)

We are trying to change the Makefile URL of a Git Project, but it won't save. :-1: :bug:

**Comment by kasperg** [comment]
The only option for changing this at the moment seems to be editing the value directly in the database.
